import { defineCorePlugin } from "..";
import { fetchTheme, themes } from "@lib/addons/themes";

const FIXED_THEMES = [
  "https://raw.githubusercontent.com/n0t-a-username/revenge-themes/refs/heads/main/DarkDiscord.json",
  "https://raw.githubusercontent.com/AsterionXeity/Aetheris/refs/heads/main/Aetheris-BG.json",
  "https://raw.githubusercontent.com/eeriemyxi/glorious-sunset/refs/heads/main/theme.json",
  "https://raw.githubusercontent.com/Purple-EyeZ/Darkened-Collection/refs/heads/main/minified_themes/Darkened_Blossom_AMOLED_min.json",
  "https://raw.githubusercontent.com/Purple-EyeZ/Darkened-Collection/refs/heads/main/minified_themes/Darkened_Acid_AMOLED_min.json",
  "https://raw.githubusercontent.com/Purple-EyeZ/Darkened-Collection/refs/heads/main/minified_themes/Darkened_Ice_AMOLED_min.json",
  "https://raw.githubusercontent.com/Purple-EyeZ/Darkened-Collection/refs/heads/main/minified_themes/Darkened_Gold_AMOLED_min.json",
  "https://raw.githubusercontent.com/Purple-EyeZ/Darkened-Collection/refs/heads/main/minified_themes/Darkened_Basic_AMOLED_min.json",
  "https://raw.githubusercontent.com/Purple-EyeZ/Darkened-Collection/refs/heads/main/minified_themes/Darkened_Barbie_AMOLED_min.json",
  "https://raw.githubusercontent.com/Purple-EyeZ/Darkened-Collection/refs/heads/main/minified_themes/Darkened_Blood_AMOLED_min.json",
  "https://raw.githubusercontent.com/Purple-EyeZ/Darkened-Collection/refs/heads/main/minified_themes/Darkened_Amethyst_AMOLED_min.json",
  "https://raw.githubusercontent.com/DEAD1nsane/Turbo/refs/heads/main/Themes/DARK/RBW%20AMOLED.json",
  "https://raw.githubusercontent.com/Rairof/Discord-Theme/main/RosieDark.json",
  "https://raw.githubusercontent.com/Gansing/discord-stuff/refs/heads/main/Purple-Serenity.json",
  "https://raw.githubusercontent.com/Gansing/discord-stuff/refs/heads/main/Deep-Waters.json",
  "https://raw.githubusercontent.com/dora727/doraa-pyoncordstuff/refs/heads/master/Themes/YouGray/YouGray.json",
  "https://raw.githubusercontent.com/dora727/doraa-pyoncordstuff/refs/heads/master/Themes/YouPink/YouPink.json",
  "https://raw.githubusercontent.com/dora727/doraa-pyoncordstuff/refs/heads/master/Themes/YouPurple/YouPurple.json",
  "https://raw.githubusercontent.com/dora727/doraa-pyoncordstuff/refs/heads/master/Themes/YouGold/YouGold.json",
  "https://raw.githubusercontent.com/dora727/doraa-pyoncordstuff/refs/heads/master/Themes/YouRed/YouRed.json",
  "https://raw.githubusercontent.com/dora727/doraa-pyoncordstuff/refs/heads/master/Themes/YouGreen/YouGreen.json",
  "https://raw.githubusercontent.com/dora727/doraa-pyoncordstuff/refs/heads/master/Themes/YouBlue/YouBlue.json",
  "https://bunny.mudaranrhiod.xyz/rosieblue.json",
  "https://raw.githubusercontent.com/jamlotrasoiaf/ThemesCorrected/refs/heads/main/ClearVision/Vendetta/ClearVision.json",
  "https://raw.githubusercontent.com/Cookietsu/VendettaTheme/main/Galaxy.json",
  "https://raw.githubusercontent.com/VodkaXMartini/VendettaTheme/main/PurpleGalaxy.json",
  "https://raw.githubusercontent.com/VodkaXMartini/VendettaTheme/main/Vision.json",
  "https://raw.githubusercontent.com/mysticentity/ThemeStrings/main/DosTerminal.json",
  "https://raw.githubusercontent.com/kmmiio99o/theme-marketplace/refs/heads/main/themes/approved/light-blossom-1756299765934.json",
  "https://raw.githubusercontent.com/kmmiio99o/theme-marketplace/refs/heads/main/themes/approved/dark-blossom-1756299787345.json",
  "https://raw.githubusercontent.com/breadcat0314/discord-themes/refs/heads/main/AMOLED.json",
  "https://raw.githubusercontent.com/kmmiio99o/discord-mobile-themes/refs/heads/main/midnight-vencord.json",
  "https://raw.githubusercontent.com/Jakutm/RevengeF1/refs/heads/main/Legends/s.json",
  "https://bunny.mudaranrhiod.xyz/eyecandy.json",
  "https://raw.githubusercontent.com/Jakutm/RevengeF1/refs/heads/main/Piastri/Piastri.json",
  "https://raw.githubusercontent.com/KKingCodesForFun/Themes/main/Theme.json",
  "https://raw.githubusercontent.com/puhboo/themes/refs/heads/main/puhbuAMOLEDTEST.json",
  "https://raw.githubusercontent.com/VodkaXMartini/EnmityTheme/main/Ukiyo.json",
  "https://raw.githubusercontent.com/VodkaXMartini/VendettaTheme/main/Orchid.json",
  "https://raw.githubusercontent.com/VodkaXMartini/VendettaTheme/main/Ataraxia.json",
  "https://q7tech.github.io/vendetta-theme/surDetta.json",
  "https://raw.githubusercontent.com/mysticentity/ThemeStrings/main/spyro.json",
  "https://raw.githubusercontent.com/mysticentity/ThemeStrings/main/Sakura.json",
  "https://raw.githubusercontent.com/maggster165/vendettathemes/main/maggiespurple.json",
  "https://raw.githubusercontent.com/kingofcube/vdthemes/main/PurpleOLED.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/mocha/yellow.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/mocha/teal.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/mocha/sky.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/mocha/sapphire.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/mocha/rosewater.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/mocha/red.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/mocha/pink.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/mocha/peach.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/mocha/mauve.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/mocha/maroon.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/mocha/lavender.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/mocha/green.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/mocha/flamingo.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/mocha/blue.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/macchiato/yellow.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/macchiato/teal.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/macchiato/sky.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/macchiato/sapphire.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/macchiato/rosewater.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/macchiato/red.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/macchiato/pink.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/macchiato/peach.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/macchiato/mauve.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/macchiato/maroon.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/macchiato/lavender.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/macchiato/green.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/macchiato/flamingo.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/macchiato/blue.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/latte/yellow.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/latte/teal.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/latte/sky.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/latte/sapphire.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/latte/rosewater.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/latte/red.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/latte/pink.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/latte/peach.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/latte/mauve.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/latte/maroon.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/latte/lavender.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/latte/green.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/latte/flamingo.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/latte/blue.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/frappe/yellow.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/frappe/teal.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/frappe/sky.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/frappe/sapphire.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/frappe/rosewater.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/frappe/red.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/frappe/pink.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/frappe/peach.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/frappe/mauve.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/frappe/maroon.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/frappe/lavender.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/frappe/green.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/frappe/flamingo.json",
  "https://raw.githubusercontent.com/catppuccin/vendetta/refs/heads/main/themes/frappe/blue.json",
  "https://raw.githubusercontent.com/luzikii/vendetta/main/CP2077HUD.json",
  "https://raw.githubusercontent.com/myrayuoo/Primrose/main/Primrose.json",
  "https://raw.githubusercontent.com/1MMM10/Gruvdetta/main/gruvboxbg.json",
  "https://raw.githubusercontent.com/Wilk-22/Material-Discord-Mobile/main/Material-Discord-Mobile.json",
  "https://raw.githubusercontent.com/denji6969/AnimeVision/main/AnimeVisionVendetta.json",
  "https://raw.githubusercontent.com/Kitomanari/vendetta-stuff/main/themes/dark-vendetta/theme.json",
  "https://raw.githubusercontent.com/olobia/iztejdziurywyskoczyeminem/main/cybpunk2077.json",
  "https://raw.githubusercontent.com/olobia/themes/main/pixelout.json",
  "https://raw.githubusercontent.com/luzikii/vendetta/main/tokyoNight.json",
  "https://raw.githubusercontent.com/ArisonID/aris-silly-themes/main/Discord'sBlurple.json",
  "https://raw.githubusercontent.com/S9Teen/Themes/main/Night%20Life.json",
  "https://raw.githubusercontent.com/TakiShiwa/Themes/main/ScarletLove/Vendetta/ScarletLove.json",
  "https://raw.githubusercontent.com/TakiShiwa/Themes/main/ClearVision/Vendetta/ClearVision.json",
  "https://raw.githubusercontent.com/ArisonID/aris-silly-themes/main/Catty.json",
  "https://raw.githubusercontent.com/VodkaXMartini/VendettaTheme-Plus/main/Midnight%20Plus.json",
  "https://raw.githubusercontent.com/VodkaXMartini/VendettaTheme-Plus/main/MidnightEspresso%20Plus.json",
  "https://raw.githubusercontent.com/VodkaXMartini/VendettaTheme-Plus/main/Vision%20pro%202.0.json",
  "https://raw.githubusercontent.com/vorlie/VendettaThemes/main/Purpdark/Purpdark_v2.json",
  "https://raw.githubusercontent.com/vorlie/VendettaThemes/main/BlueVen/BlueVen.json",
  "https://raw.githubusercontent.com/vorlie/VendettaThemes/main/PurpAMOLED/PurpAMOLED.json",
  "https://raw.githubusercontent.com/vorlie/VendettaThemes/main/RedFeathers/redfeathers.json",
  "https://raw.githubusercontent.com/vorlie/VendettaThemes/main/MediumSlateBlue/MediumSlateBlue.json",
  "https://raw.githubusercontent.com/vorlie/VendettaThemes/main/SeaGreen/SeaGreen.json",
  "https://raw.githubusercontent.com/vorlie/VendettaThemes/main/Purpdark/Purpdark_BG/Purpdark_v3.json",
  "https://raw.githubusercontent.com/vorlie/VendettaThemes/main/Nord/nord.json",
  "https://raw.githubusercontent.com/ArisonID/aris-silly-themes/main/TheEveningSkies.json",
  "https://raw.githubusercontent.com/ArisonID/aris-silly-themes/main/WavyPink.json",
  "https://raw.githubusercontent.com/TakiShiwa/Themes/main/Ratio/Vendetta/Ratio.json",
  "https://raw.githubusercontent.com/TakiShiwa/Themes/main/VendettaTeal/Vendetta/AMOLED.json",
  "https://raw.githubusercontent.com/ArisonID/aris-silly-themes/main/Wavy.json",
  "https://raw.githubusercontent.com/Mateusussy210/explod/main/Roze%20Quartz_poly.json",
  "https://raw.githubusercontent.com/TakiShiwa/Themes/main/GruvYellow/Vendetta/GruvYellow.json",
  "https://luckfire.github.io/vendetta-themes/src/themes/Tachiyomi-Lavender.json",
  "https://raw.githubusercontent.com/squat9042/vendetta-themes/main/Fade.json",
  "https://raw.githubusercontent.com/squat9042/vendetta-themes/main/Whatsdetta.json",
  "https://raw.githubusercontent.com/ArisonID/aris-silly-themes/main/RosieSkies.json",
  "https://raw.githubusercontent.com/ArisonID/aris-silly-themes/main/VioletSkies.json",
  "https://raw.githubusercontent.com/Azakidev/dracula-aliucordRN/vendetta/Dracula.json",
  "https://raw.githubusercontent.com/Wizzy-TV/VendettaThemes/main/PixelCityLite/pixelcity-lite.json",
  "https://raw.githubusercontent.com/ArisonID/aris-silly-themes/main/Sh%C5%8Dgen.json",
  "https://raw.githubusercontent.com/Wizzy-TV/VendettaThemes/main/PixelCity/pixelcity.json",
  "https://raw.githubusercontent.com/ArisonID/aris-silly-themes/main/BlueySkies.json",
  "https://raw.githubusercontent.com/Wizzy-TV/VendettaThemes/main/OrangeOLED/OrangeOLED.json",
  "https://raw.githubusercontent.com/Wizzy-TV/VendettaThemes/main/PurpleMountains/purple-mountains.json",
  "https://raw.githubusercontent.com/ArisonID/aris-silly-themes/main/MaroonSkies.json",
  "https://raw.githubusercontent.com/VodkaXMartini/VendettaTheme/main/Katana.json",
  "https://raw.githubusercontent.com/Wizzy-TV/VendettaThemes/main/Vulcan/vulcan.json",
  "https://raw.githubusercontent.com/Wizzy-TV/VendettaThemes/main/AmoledOrangeMountains/amoled-orange-mountains.json",
  "https://raw.githubusercontent.com/Mazetta/vd-themes/main/Alicorn-V2.json",
  "https://raw.githubusercontent.com/laser4/Krimson-Scarlet/main/krimson.json",
  "https://raw.githubusercontent.com/Wizzy-TV/VendettaThemes/main/OrangeMountains/orangemountains.json",
  "https://raw.githubusercontent.com/laser4/silver-sliver/main/silversliver.json",
  "https://raw.githubusercontent.com/VodkaXMartini/VendettaTheme/main/PurpleKittyVd.json",
  "https://raw.githubusercontent.com/Wizzy-TV/VendettaThemes/main/OneColor/onecolor.json",
  "https://raw.githubusercontent.com/VodkaXMartini/VendettaTheme/main/Pebble.json",
  "https://raw.githubusercontent.com/VodkaXMartini/VendettaTheme/main/Midnight-Espresso.json",
  "https://nyri4.github.io/LilyPichu/vendetta/lilypichu.json",
  "https://raw.githubusercontent.com/ArisonID/aris-silly-themes/main/Origins_Lemon_Yellow.json",
  "https://raw.githubusercontent.com/ArisonID/aris-silly-themes/main/Origins_Rose_Red.json",
  "https://raw.githubusercontent.com/cyriotic3/VendettaThemes/main/rogueplus.json",
];

function getThemeName(url: string): string {
  const filename = url.split('/').pop() || "Unknown";
  return filename.replace('.json', '').replace(/%20/g, ' ');
}

export default defineCorePlugin({
    manifest: {
        id: "bunny.fixedthemes",
        version: "1.0.0",
        type: "plugin",
        spec: 3,
        main: "",
        display: {
            name: "Temas Fixos",
            description: "Carrega lista fixa de temas",
            authors: [{ name: "V1VEU" }]
        }
    },

    start() {
        FIXED_THEMES.forEach(url => {
            if (!(url in themes)) {
                fetchTheme(url, false).catch(() => {
                    // Silently fail if theme doesn't load
                });
            }
        });
    }
});
