name: Build BTLoader
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Theos
      run: |
        git clone https://github.com/theos/theos.git ~/theos
        echo 'export THEOS=~/theos' >> ~/.bashrc
        
    - name: Install SDK
      run: |
        mkdir -p ~/theos/sdks
        wget https://github.com/theos/sdks/releases/download/master-146e41f/iPhoneOS13.7.sdk.tar.xz
        tar -xf iPhoneOS13.7.sdk.tar.xz -C ~/theos/sdks/
        
    - name: Install Dependencies
      run: |
        brew install llvm
        
    - name: Build BTLoader
      run: |
        cd 
        export THEOS=~/theos
        make SDK=iphoneos13.7 CFLAGS="-Wno-error -Wno-deprecated"
        
    - name: Upload BTLoader.dylib
      uses: actions/upload-artifact@v4
      with:
        name: BTLoader
        path: obj/BTLoader.dylib
